### ISSUE TITLE
Long-running use of 'display' exhausts disk space in /tmp and kills process due to not removing temporary files

### ISSUE THREAD

**Issue by gwern** [szym/display#11]
I was running dcgan.torch for 4 days and it had finally begun to learn to generate images which looked a little like the originals, and I was very excited. Then it crashed because it tried to write a file to /tmp and it had run out of space, due to thousands upon thousands of files named '/tmp/lua*', which turned out to be the visualizations in the local server hanging around for some reason. (I had several gigabytes of free space on / originally, but not enough, apparently.) After looking through dcgan.torch's source and seeing nothing that looked like it would be responsible for littering /tmp/ like that, I checked 'display' and it seems that this is deliberate:

```
function M.image(img, opts)
  -- options:
  opts = opts or {}
  local win = opts.win or uid()      -- id of the window to be reused
...
  img = normalize(img, opts)

  -- I wish we could write to memory instead of on-disk file.
  local filename = os.tmpname() .. '.png'
  image.save(filename, img)

  local file = io.open(filename, 'rb')
  local imgdata = 'data:image/png;base64,' .. mime.b64(file:read('*all'))
  file:close()

  send({ command='image', id=win, src=imgdata, labels=opts._labels, width=opts.width, title=opts.title })
  return win
end
```

That is, each image displayed gets copied to /tmp/ along with another empty file and they never get deleted.

I infer that the idea is that the HTML source code sent to the browser by the local server is including a image href of '/tmp/luaxxx.png' and this is what the browser is following and displaying, and the mention of asynchronous suggests that the rationale for leaving all images written to disk & taking up space in /tmp/ is that they cannot be removed immediately lest there be a race condition with the browser trying to read the image from disk to display it.

I'm not a Lua programmer so I don't know what the fix here is, but perhaps the images could be sent inline in base64 encoding as a string so they need never be written in the first place? Or perhaps the call could be made synchronous and the display function clean up after itself once the browser finishes?

In the mean time, a hack to work around it is to simply delete all reasonably old 'lua'-named intermediate files in a while loop:

```
while true; do find /tmp/ -maxdepth 1 -type f -cmin +10 -name "lua*" -delete; sleep 10m; done
```

**Comment by gwern** [comment]
Another suggestion: one reason people would not be happy with that `find` workaround, and might not want to put it in their own programs to workaround `display`'s problem, is that they are worried that by deleting everything prefixed "lua", they might cause subtle bugs for other programs. `display` could reduce the odds of this happening by adding additional metadata into the temporary filenames. For example, change

```
local filename = os.tmpname() .. '.png'
```

to something like

```
local filename = os.tmpname() .. 'display.png'
```

Then the glob can be made more precise. Or even more precisely, perhaps call something like [processid](http://wiki.alpinelinux.org/wiki/LuaPosix#getprocessid) to encode the creating process's ID into the temporary filenames, and then any longrunning program worried about running out of space can simply get its own PID and kill only those.

**Comment by soumith** [comment]
@gwern i feel very bad now, that you kept it up for 4 days. With GPUs, it simply takes 3-4 hours to get to good images.

wrt display using temp images, i will prepare a patch, we can do all of this in-memory using image.compressJPG ( https://github.com/torch/image/blob/master/doc/saveload.md#res-imagecompressjpgtensor-quality )

**Comment by soumith** [comment]
sent a PR via #12

**Comment by gwern** [comment]
> With GPUs, it simply takes 3-4 hours to get to good images.

Yeah, I know that simpler sets of images like faces or flowers run much faster. But I was curious to see how complex and heterogeneous a set of imageclasses can be handled; it may be that people underestimate how much complexity dcgan.torch can model because they haven't run it long enough for the gradual progress to go somewhere interesting...

(I have no comments on the patch/PR since I don't know enough Lua to judge it. If it works, great and thanks.)

**Comment by szym** [comment]
@gwern Sorry to hear about the failure. Hopefully, display won't run out of resources after soumith's fix.
