### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by OptimusLime** [szym/display#17]
I'm looking for a way to scale/zoom images in the browser (much like you can send scale to image.display) 

Any way to scale the image without performing a scale operation to the torch tensor in lua?

**Comment by szym** [comment]
There's two options. Neither of them require scaling the tensor:
1. Use the `width` option:
   
   ```
   disp = require 'display'
   disp.image(img, { width=200 })
   ```
2. Use your mouse scroll to zoom the image once displayed in the display workspace.
