### ISSUE TITLE
installation problem 

### ISSUE THREAD

**Issue by chuanli11** [szym/display#19]
Hi, 

I got the following error during installation

mkdir /home/chuan/torch/install/lib/luarocks/rocks/display/scm-0/lua/display && cp -a static plugins /home/chuan/torch/install/lib/luarocks/rocks/display/scm-0/lua/display
cp: cannot stat ‘plugins’: No such file or directory

It seems to be related to the recent update in display-scm-0.rockspec

Any idea how to fix this? Thanks.

**Comment by szym** [comment]
Sorry about that, I've been working on adding a framework for plugins. Fixed.
