### ISSUE TITLE
display not working on localhost -- only showing json info, but not image

### ISSUE THREAD

**Issue by suryabhupa** [szym/display#20]
In following the tutorial on the README, when the display function runs, but only is outputting the json: data: {"content":{"file":[[0,-1.2920932073243],[1.1111111111111,-1.0734784297415],[2.2222222222222,0.27885892990331],[3.3333333333333,-0.12175768971955],[4.4444444444444,0.16801618442082],[5.5555555555556,0.011533429745621],[6.6666666666667,0.83489397687172],[7.7777777777778,0.031249044780407],[8.8888888888889,0.23550898868986],[10,-0.6444625754049]]},"command":"pane","id":"pane_145713209407532286166836","type":"plot"}

Is there something that's happening, and something I can do to resolve this? This same issue is also happening when running MazeBase from Facebook -- it shows the json, and not the actual images.

**Comment by szym** [comment]
I'm not sure what MazeBase is.

Can you help me figure this out? Which step in the tutorial produces the output?

**Comment by suryabhupa** [comment]
I first ran:

`th -ldisplay.start 8000 0.0.0.0
`

and on a separate terminal, I ran this:

`th example.lua
`

to which the output in localhost:8000/events is:

> data: {"title":"lena","content":{"src":"data:image\/jpg;base64,\/9j\/4AAQSkZJRgABAQAAAQABAAD\/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL\/2wBDA...

Basically, the json isn't being decoded, and it's just a big dump of the base64 information of the image.

**Comment by soumith** [comment]
where exactly did you read that you should open localhost:8000/events ?

**Comment by suryabhupa** [comment]
In the terminal where I ran the start to the server, it printed out lines like:

`POST   /events
POST    /events
POST    /events
POST    /events
POST    /events
POST    /events
GET /
`

so I assumed the images were being posted there, and I only see the dumps. Otherwise, if I keep localhost:8000 open while running `th example.lua`, it just says "Not found!" Am I missing a step somewhere?

**Comment by soumith** [comment]
the README quickstart says https://github.com/szym/display#-quick-start

Then open http://(hostname):(port)/ in your browser to load the remote desktop.

try that.

**Comment by soumith** [comment]
if that says Not found! that seems to be a problem. you should see the display webpage, and when events happen, you see images, plots etc.

**Comment by suryabhupa** [comment]
Yeah, it seems like whenever I start the server, it just says "Not found!" on localhost:8000. Do you think there's some configuration error? When I try to use Mazebase, the same issue happens (which I assume is because this isn't working either). 

This is happening on my friend's computer as well, and she is following the same setup.

**Comment by soumith** [comment]
try to change the port and see what happens. maybe there's something else running on localhost:8000

Also, what browser are you opening this in?
And what folder are you running this from?

**Comment by suryabhupa** [comment]
I just changed it to localhost:2345 and localhost:4567, and tried it on Safari and Google Chrome, and it's still saying "Not found!" I'm running this from the root of the display repo. Should I try from elsewhere?

**Comment by soumith** [comment]
try it from another folder, other than from the root of the display repo. try it from your home directory or something.

**Comment by soumith** [comment]
i cant reproduce your issue though, weird.

**Comment by szym** [comment]
"Not found" is a strange result given that http://localhost:8000/events seems to work as expected (though it is not meant to be opened by the user).

Try opening http://localhost:8000/index.html

**Comment by szym** [comment]
Ah, now I see what could be causing it. Maybe `sys.fpath()` does not work as expected?

**Comment by szym** [comment]
OK I think thus is the bug. Server.lua concatenates sys.fpath() with '/static'. Surprised I didn't catch it.

**Comment by szym** [comment]
That should fix it. Can you try with the new HEAD?

**Comment by suryabhupa** [comment]
Gah, it still says "Not found!" :/ Even opening localhost:8000/index.html shows the same message. 

Just to make sure we're on the same page, I'm running `th -ldisplay.start 8000` from my home directory, trying to go to localhost:8000, and this is the message.

**Comment by soumith** [comment]
try: luarocks install display
That will update your installed display to head

**Comment by suryabhupa** [comment]
Yeah, I pulled the repo and did luarocks install display, but the same is showing up here and on my friend's computer.

**Comment by soumith** [comment]
oh god, yea i'm sorry just got a repro. will fix in a sec.

**Comment by suryabhupa** [comment]
Haha, whew -- I really thought my setup was just completely whack. Hopefully it works out.

**Comment by soumith** [comment]
sent a PR #21 to fix it.

If you want to try it immediately:

``` bash
cd /tmp
git clone https://github.com/soumith/display -b fixpaths
cd display
luarocks make
cd
th -ldisplay.start
```

**Comment by suryabhupa** [comment]
It seems to still suffer from the same problem even after pulling from luarocks install display :/ Running `th -ldisplay.start 8000 0.0.0.0` still shows "Not found!" on 0.0.0.0:8000.

**Comment by suryabhupa** [comment]
Are there any other dependencies that I should have?

**Comment by soumith** [comment]
try it again now. (had to update the rock https://github.com/torch/rocks/commit/7ff94c566e15eabe03465b3202deed46bf9dc133 )

luarocks install display
th -ldisplay.start

**Comment by suryabhupa** [comment]
It works! :+1: Thank you so much for all of this.
