### ISSUE TITLE
doesn't seem to work within a non root path eg. http://example.com:8889/display/

### ISSUE THREAD

**Issue by zig** [szym/display#24]
I want to put display behind a proxy which serves other sites, so I can't use / as path for display, however it seems we can only configure the hostname and port, not the root path.

**Comment by szym** [comment]
What happens if you try to specify

```
display.url = 'http://example.com:8889/display/'
```

**Comment by zig** [comment]
Actually, I meant for the browser client. What you suggest I think address the problem for the application doing the drawing. In my case, the application runs on the same host as the display server so it can access it normally (http://localhost:8889/)

It seems I didn't properly configure my reverse proxy (nginx), now by changing a bit the config file, it is  working. Here's my config now, that seems to work :

```
        location /display/ {
                proxy_pass http://172.17.0.3:8889/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Origin "";
        }
```

What I was missing initially was to handle websockets, apparently they are used by display, I was not aware.

I have another problem now : my proxy is ssl enabled (https), with ssl there's an error given by the browser. I'll open another issue for this, and I close this one since it seems it was bogus.
