### ISSUE TITLE
Can I redraw the last 10 windows?

### ISSUE THREAD

**Issue by soumith** [szym/display#3]
gfx had this ability to redraw windows you lost (let's say you closed the browser). gfx.redraw(10) redrew the last 10 windows.

Does display still retain that functionality?

**Comment by szym** [comment]
No, the server has no state at all. Theoretically, the client could remember the windows in LocalStorage, but the space there is limited to 10MB.

**Comment by szym** [comment]
Could also mimic this behavior by having a local cache in the torch/python backend (cache the messages before sending them to the server).

**Comment by soumith** [comment]
cool, thanks. I was assuming that the files might still be sticking around on the filesystem.
