### ISSUE TITLE
Error: Failed installing dependency: http://luarocks.org/repositories/rocks/async-1.1-1.rockspec - Could not satisfy dependency: love ~> 0.9

### ISSUE THREAD

**Issue by c1a1o1** [szym/display#31]
Error: Failed installing dependency: http://luarocks.org/repositories/rocks/async-1.1-1.rockspec - Could not satisfy dependency: love ~> 0.9

how to  install love

**Comment by szym** [comment]
The `async` package in the `luarocks.org` repository is a different package than http://github.com/clementfarabet/async

Make sure that you are using the torch rocks repo: http://htmlpreview.github.io/?https://github.com/torch/rocks/blob/master/index.html
