### ISSUE TITLE
throwing error on display.image

### ISSUE THREAD

**Issue by michaelByrne** [szym/display#36]
Hi, I'm running on an EC2 instance and trying to get a basic remote desktop going to view images. Following the readme, and in other attempts (such as displaying a basic jpg), I get the following error:

```
.../ubuntu/torch/install/share/lua/5.1/display/init.lua:71: attempt to index local 'img' (a nil value)
stack traceback:
	.../ubuntu/torch/install/share/lua/5.1/display/init.lua:71: in function 'image'
	stdin:1: in main chunk
	[C]: ?

```
I see in the file in question that the image module is marked 'broken.' Is there a workaround? I'm able to send plots and text just fine. 

Thanks, 

- michael

**Comment by soumith** [comment]
@michaelByrne in your case, looks like you are calling disp.image with an empty or nil arguments, i.e. you are not passing in an img argument in to this function in the first place.

**Comment by michaelByrne** [comment]
Thanks for the quick reply. I was trying to get a test tensor via image.load and passing in the result, which was nil as it turns out. I made a 3D tensor just by the Torch method and was indeed able to display it. 

Thanks!
