### ISSUE TITLE
display.image Images no Longer Zoom

### ISSUE THREAD

**Issue by mathewhall** [szym/display#42]
In the zoom function, self.width and self.height (in panes.js lines 451 and 452) are always 0 (so the image disappears when a user tries to zoom by scrolling).  It doesn't seem to be due to an update in the display utility, but I'm wondering if anyone else has experienced this issue and has tracked down a root cause.

**Comment by ashafaei** [comment]
See https://github.com/szym/display/pull/40
I don't know know why it is not merged yet.

**Comment by mathewhall** [comment]
Thanks so much!
